import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import localFont from 'next/font/local';

import './globals.css';
import Header from './ui/components/header';
import Footer from './ui/components/footer';
import SocialMedia from './ui/components/socialMedia';

const plus_jakarta_sans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  display: 'fallback',
  variable: '--font-jakarta-sans',
});
const inter = localFont({
  src: './ui/fonts/Bebas_Neue/BebasNeue-Regular.ttf',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plus_jakarta_sans.className}>
        <Header />

        {children}
        <SocialMedia />
        <Footer />
      </body>
    </html>
  );
}
